package com.dollarandtrump.daogenerator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dollarandtrump.daogenerator.PostCarDB;

import com.dollarandtrump.daogenerator.PostCarDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig postCarDBDaoConfig;

    private final PostCarDBDao postCarDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        postCarDBDaoConfig = daoConfigMap.get(PostCarDBDao.class).clone();
        postCarDBDaoConfig.initIdentityScope(type);

        postCarDBDao = new PostCarDBDao(postCarDBDaoConfig, this);

        registerDao(PostCarDB.class, postCarDBDao);
    }
    
    public void clear() {
        postCarDBDaoConfig.getIdentityScope().clear();
    }

    public PostCarDBDao getPostCarDBDao() {
        return postCarDBDao;
    }

}
