package com.dollarandtrump.daogenerator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "POST_CAR_DB".
 */
public class PostCarDB {

    private Long id;
    private Integer CarId;
    private Integer CarYear;
    private Integer Gear;
    private String ShopRef;
    private String BrandName;
    private String CarSub;
    private String CarSubDetail;
    private String CarDetail;
    private String CarPrice;
    private String CarStatus;
    private String Plate;
    private String Name;
    private Integer ProvinceId;
    private String ProvinceName;
    private String TelNumber;
    private java.util.Date DateModifyTime;
    private String CarImagePath;

    public PostCarDB() {
    }

    public PostCarDB(Long id) {
        this.id = id;
    }

    public PostCarDB(Long id, Integer CarId, Integer CarYear, Integer Gear, String ShopRef, String BrandName, String CarSub, String CarSubDetail, String CarDetail, String CarPrice, String CarStatus, String Plate, String Name, Integer ProvinceId, String ProvinceName, String TelNumber, java.util.Date DateModifyTime, String CarImagePath) {
        this.id = id;
        this.CarId = CarId;
        this.CarYear = CarYear;
        this.Gear = Gear;
        this.ShopRef = ShopRef;
        this.BrandName = BrandName;
        this.CarSub = CarSub;
        this.CarSubDetail = CarSubDetail;
        this.CarDetail = CarDetail;
        this.CarPrice = CarPrice;
        this.CarStatus = CarStatus;
        this.Plate = Plate;
        this.Name = Name;
        this.ProvinceId = ProvinceId;
        this.ProvinceName = ProvinceName;
        this.TelNumber = TelNumber;
        this.DateModifyTime = DateModifyTime;
        this.CarImagePath = CarImagePath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCarId() {
        return CarId;
    }

    public void setCarId(Integer CarId) {
        this.CarId = CarId;
    }

    public Integer getCarYear() {
        return CarYear;
    }

    public void setCarYear(Integer CarYear) {
        this.CarYear = CarYear;
    }

    public Integer getGear() {
        return Gear;
    }

    public void setGear(Integer Gear) {
        this.Gear = Gear;
    }

    public String getShopRef() {
        return ShopRef;
    }

    public void setShopRef(String ShopRef) {
        this.ShopRef = ShopRef;
    }

    public String getBrandName() {
        return BrandName;
    }

    public void setBrandName(String BrandName) {
        this.BrandName = BrandName;
    }

    public String getCarSub() {
        return CarSub;
    }

    public void setCarSub(String CarSub) {
        this.CarSub = CarSub;
    }

    public String getCarSubDetail() {
        return CarSubDetail;
    }

    public void setCarSubDetail(String CarSubDetail) {
        this.CarSubDetail = CarSubDetail;
    }

    public String getCarDetail() {
        return CarDetail;
    }

    public void setCarDetail(String CarDetail) {
        this.CarDetail = CarDetail;
    }

    public String getCarPrice() {
        return CarPrice;
    }

    public void setCarPrice(String CarPrice) {
        this.CarPrice = CarPrice;
    }

    public String getCarStatus() {
        return CarStatus;
    }

    public void setCarStatus(String CarStatus) {
        this.CarStatus = CarStatus;
    }

    public String getPlate() {
        return Plate;
    }

    public void setPlate(String Plate) {
        this.Plate = Plate;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public Integer getProvinceId() {
        return ProvinceId;
    }

    public void setProvinceId(Integer ProvinceId) {
        this.ProvinceId = ProvinceId;
    }

    public String getProvinceName() {
        return ProvinceName;
    }

    public void setProvinceName(String ProvinceName) {
        this.ProvinceName = ProvinceName;
    }

    public String getTelNumber() {
        return TelNumber;
    }

    public void setTelNumber(String TelNumber) {
        this.TelNumber = TelNumber;
    }

    public java.util.Date getDateModifyTime() {
        return DateModifyTime;
    }

    public void setDateModifyTime(java.util.Date DateModifyTime) {
        this.DateModifyTime = DateModifyTime;
    }

    public String getCarImagePath() {
        return CarImagePath;
    }

    public void setCarImagePath(String CarImagePath) {
        this.CarImagePath = CarImagePath;
    }

}
