package com.dollarandtrump.angelcar.model;

/********************************************
 * Created by HumNoy Developer on 13/7/2559.
 * ผู้คร่ำหวอดในกวงการ Android มากกว่า 1 ปี
 * AngelCarProject
 ********************************************/
public enum TypeBrand {
    TOYOTA, HONDA, ISUZU, NISSAN, MITSUBISHI, BMW, MERCEDES_BENZ, ABARTH,
    ALFA_ROMEO, AMC, ASTON_MARTIN, ATTHAM, AUDI, AUSTIN, BENTLEY, BUICK,
    CADILLAC, CHERY, CHEVROLET, CHRYSLER, CITROEN, DAEWOO, DAIHATSU,
    DATSUN, DEVA, DFM, DFSK, DKW, DODGE, FERRARI, FIAT, FORD, FOTON, GMC,
    HIGER, HINO, HOLDEN, HUMMER, HYUNDAI, INFINITI, JAGUAR, JEEP, JOYLONG,
    KIA, LAMBORGHINI, LANCIA, LAND_ROVER, LEXUS, LINCOLN, LOTUS, MASERATI,
    MAZDA, MERCURY, MG, MINI, MITSUOKA, MUSSO, NAZA, OLDSMOBILE, OPEL, PERODUA,
    PEUGEOT, PONTIAC, PORSCHE, PROTON, ROLLS_ROYCE, ROVER, SAAB, SEAT, SKODA,
    SMART, SSANGYONG, SUBARU, SUZUKI, TATA, TESLA, THAI_RUNG, VOLKSWAGEN, VOLVO, WULING
}
